### PR TITLE
Fix the regular expression to check the method and extract URI options according to RFC3986:

### LINKED ISSUE #2: Several HTTP methods not supported and URL options not parsed correctly
I'm porting Ada Servlet and OpenAPI Ada on top of EWS and I've reached some minor problems that can easily be fixed (I'll submit a pull request).

## HTTP Methods

Only `POST` and `GET` methods are recognized but for some REST API it is highly desirable to support also the `HEAD`, `OPTIONS`, `PUT`, `DELETE` and `PATCH` methods.

## Options

Extraction of options failed to recognize the URL when the options part contains some characters like `"` or `:`.
Below is the HTTP GET method produced by AWS:

```
GET /v1/testTextResponse?options=test%20content%20'%3C%3E;:" HTTP/1.1
Accept: text/plain
Connection: Close
Host: localhost:8082
Accept-Encoding: gzip, deflate
Accept-Language: fr, ru, us
User-Agent: AWS (Ada Web Server) v20.0
```

And according to RFC 3986, they recommend to use the following regex to match the URI:
```
^(([^:/?#]+):)?(//([^/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?
```

### PR DESCRIPTION
**Pull request by stcarrez**
- recognize HEAD, OPTIONS, PUT, DELETE, PATCH methods,
- allow to extract URI options for the HTTP OPTIONS method,
- fix the extraction of query options to take into account the '?'
Fixes #2

### CODE REVIEW

**Comment by simonjwright** [comment]
I’m not familiar with the full gamut of methods - but would have expected there to be some processing associated with them? The patch processes OPTIONS exactly like GET and ignores HEAD PUT DELETE PATCH.

(sorry if I’ve missed the obvious - tested positive this morning)

**Comment by stcarrez** [comment]
Good remark.
There are two ways to pass parameters:
* in the request URI
* in the request body

The `GET`, `HEAD`, `OPTIONS` don't have a body and the parameters are passed only through URI.
For `PUT`, `POST`, `DELETE` and `PATCH` since a request body can be defined, you have both ways.

I'll update the pull request.

> (sorry if I’ve missed the obvious - tested positive this morning)

Oops.... hope you'll be safe and recover soon!

**Comment by simonjwright** [comment]
Merged: I’ll be updating my copyright notices anyway, would you like me to add yours?

**Comment by stcarrez** [comment]
Thanks Simon! It's fine for me!

**Comment by simonjwright** [comment]
Sorry, was that "yes, please add me" or "no, don’t bother"?

**Comment by stcarrez** [comment]
Yes, as small contributor

**Pull request merged**
